name: Test branch

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  test-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm install && npm run lerna:exec:changed -- npm ci

      - run: npm run build:changed

      - run: npm run test:changed
